plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: false
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - docs/format_scan.md
  - docs/format.md
  - docs/utils.md
